### ISSUE TITLE
Strict/Relaxed JSON syntax

### ISSUE THREAD

**Issue by miloyip** [miloyip/rapidjson#36]
Currently RapidJSON is tried to be as strict as possible to the JSON spec.
There are several requests in adding relaxed JSON syntax for parsing. Here lists some possible ones.

Root JSON type
- [x] A document with types other than object and array. (Done in #101)

Comment
- [x] Single line JS Comment (#443)
- [x] Multiple line JS Comment (#443)
- [ ] Comment handler event
- [ ] Comment stored in Value

Object
- [ ] Key without quotes (limited to a sequence of confined character sets, e.g. `(A-Za-z\-_)+[0-9A-Za-z\-_]*`
- [x] extra comma at the end (#584)

Array
- [x] extra comma at the end (#584)

String
- [ ] Single quote pair

Number
- [ ] Fractions begins with `.`, e.g. `.123`
- [ ] Number with '.' but without fraction digits, e.g. `0.`, `123.`
- [ ] Hexadecimal integer, e.g. `0xDEADBEEF`
- [X] `Infinity` and `NaN` (#641)

These relaxed syntax may be useful for some applications. However, this may increase complexity of code base.

Would like to gather opinions on this.

**Comment by andrusha97** [comment]
Hi. Is this issue still active? I'd like to have support of comments because I use RapidJson to parse config files.
May I help with the implementation to speed-up the process?

**Comment by M1chae1** [comment]
If you just want to trim out the comments in JSON file before load into rapidjson, you can reference jsmin class used in the below open source project.

https://code.google.com/p/page-speed/source/browse/lib/trunk/src/third_party/jsmin/cpp/?r=339

Then using MemoryStream to load the minified string and parse the stream with rapidjson::Document.ParseStream to do so.

**Comment by andrusha97** [comment]
@M1chae1, I wouldn't like to use this method because:
1) Double parsing is a kludge, and continuing using my fork of rapidjson with comments support is better than using a kludge.
2) The most important thing: currently, if a config is invalid, my parser reports line number and column of the error. With this minifier it will be impossible.

**Comment by miloyip** [comment]
@andrusha97 This issue is still active. I am now preparing for 1.0 release and these features will be added afterwards. If you would like to, you may implement your solution and I will adapt or take it as a reference.

**Comment by ErikFr** [comment]
I would argue very much to keep Rapidjson as strict/standard compliant as possible by default. If a non-standard syntax should be supported, I think the user have to set some flags/options or whatever so that he/she actually have to make an effort to support the non-standard behaviour.

I have seen way too many examples of applications supporting non-standard things just for the case of simplicity. It might be nice and convenient at the time of implementation, but in the long run it will nearly always lead to problems in one way or another.

**Comment by miloyip** [comment]
@ErikFr I agree.

**Comment by kenrobbins** [comment]
Excuse my ignorance, but why wouldn't `NaN` or `Infinity` (ignoring `-Infinity`) be parsed the same way as `true` or `false` or `null`? I'm asking after seeing comments above about more sophisticated tokenizers and alternate parsing. Thanks.

**Comment by miloyip** [comment]
@kenrobbins Those can be implemented. It is a matter of fact that the standard does not support those. If we want to support that, it may need to set a spec for this. Different users/languages may uses different strings for those values. Also, some may need to handle negative infinity, some may not, for example.

**Comment by Nelvin** [comment]
I'd like to add my vote for comments and trailing commas.
A solution where these would require to be activated by the developer would be great.

Many thanks for rapidjson - seems to be a really great lib (I just started to use it today).

**Comment by miloyip** [comment]
I merged #443 for parsing single/multiple line comments, contributed by @andrusha97 .
This does not generate SAX events, nor stored in DOM. So roundtrip is not supported now.

**Comment by 1354092549** [comment]
I think we need to provide a flag to support [JSON5](http://json5.org/) 
Becasue now more and more JSON are written by humans
